//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightBalancePlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeightBalancePlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Baggage.
        /// </summary>
        public static string AddBaggage {
            get {
                return ResourceManager.GetString("AddBaggage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add baggage to the aircraft load.
        /// </summary>
        public static string AddBaggageTooltip {
            get {
                return ResourceManager.GetString("AddBaggageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Passenger.
        /// </summary>
        public static string AddPassenger {
            get {
                return ResourceManager.GetString("AddPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a passenger to the aircraft load.
        /// </summary>
        public static string AddPassengerTooltip {
            get {
                return ResourceManager.GetString("AddPassengerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft.
        /// </summary>
        public static string Aircraft {
            get {
                return ResourceManager.GetString("Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft ID.
        /// </summary>
        public static string AircraftID {
            get {
                return ResourceManager.GetString("AircraftID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight + Balance.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baggage.
        /// </summary>
        public static string Baggage {
            get {
                return ResourceManager.GetString("Baggage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baggage Spaces.
        /// </summary>
        public static string BaggageSpaces {
            get {
                return ResourceManager.GetString("BaggageSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center of Gravity.
        /// </summary>
        public static string CenterGravity {
            get {
                return ResourceManager.GetString("CenterGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copilot.
        /// </summary>
        public static string Copilot {
            get {
                return ResourceManager.GetString("Copilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Baggage Configuration.
        /// </summary>
        public static string EditBaggageConfiguration {
            get {
                return ResourceManager.GetString("EditBaggageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Envelope.
        /// </summary>
        public static string EditEnvelope {
            get {
                return ResourceManager.GetString("EditEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Load Envelope.
        /// </summary>
        public static string EditLoadEnvelope {
            get {
                return ResourceManager.GetString("EditLoadEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Seat Configuration.
        /// </summary>
        public static string EditSeatConfiguration {
            get {
                return ResourceManager.GetString("EditSeatConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Weight.
        /// </summary>
        public static string EmptyWeight {
            get {
                return ResourceManager.GetString("EmptyWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroute Burn (Gallons).
        /// </summary>
        public static string EnrouteBurn {
            get {
                return ResourceManager.GetString("EnrouteBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Capacity.
        /// </summary>
        public static string FuelCapacity {
            get {
                return ResourceManager.GetString("FuelCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing.
        /// </summary>
        public static string Landing {
            get {
                return ResourceManager.GetString("Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing Weight.
        /// </summary>
        public static string LandingWeight {
            get {
                return ResourceManager.GetString("LandingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Ramp Weight.
        /// </summary>
        public static string MaxRampWeight {
            get {
                return ResourceManager.GetString("MaxRampWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Takeoff Weight.
        /// </summary>
        public static string MaxTakeoffWeight {
            get {
                return ResourceManager.GetString("MaxTakeoffWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Weight.
        /// </summary>
        public static string MaxWeight {
            get {
                return ResourceManager.GetString("MaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment.
        /// </summary>
        public static string Moment {
            get {
                return ResourceManager.GetString("Moment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Category.
        /// </summary>
        public static string NormalCategory {
            get {
                return ResourceManager.GetString("NormalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Category Color.
        /// </summary>
        public static string NormalCategoryColor {
            get {
                return ResourceManager.GetString("NormalCategoryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Cateogry Line Style.
        /// </summary>
        public static string NormalCategoryLineStyle {
            get {
                return ResourceManager.GetString("NormalCategoryLineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Packages.
        /// </summary>
        public static string NuGetPackages {
            get {
                return ResourceManager.GetString("NuGetPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string Passenger {
            get {
                return ResourceManager.GetString("Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        public static string Pilot {
            get {
                return ResourceManager.GetString("Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot Seats.
        /// </summary>
        public static string PilotSeats {
            get {
                return ResourceManager.GetString("PilotSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Site.
        /// </summary>
        public static string ProjectSite {
            get {
                return ResourceManager.GetString("ProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Weight.
        /// </summary>
        public static string RampWeight {
            get {
                return ResourceManager.GetString("RampWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Baggage.
        /// </summary>
        public static string RemoveBaggage {
            get {
                return ResourceManager.GetString("RemoveBaggage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Passenger.
        /// </summary>
        public static string RemovePassenger {
            get {
                return ResourceManager.GetString("RemovePassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected item from the aircraft load .
        /// </summary>
        public static string RemoveTooltip {
            get {
                return ResourceManager.GetString("RemoveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Crew.
        /// </summary>
        public static string RequiredCrew {
            get {
                return ResourceManager.GetString("RequiredCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        public static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Annotation Detail.
        /// </summary>
        public static string ShowAnnotationDetail {
            get {
                return ResourceManager.GetString("ShowAnnotationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Legend.
        /// </summary>
        public static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Fuel (Gallons).
        /// </summary>
        public static string StartingFuel {
            get {
                return ResourceManager.GetString("StartingFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff.
        /// </summary>
        public static string Takeoff {
            get {
                return ResourceManager.GetString("Takeoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff Weight.
        /// </summary>
        public static string TakeoffWeight {
            get {
                return ResourceManager.GetString("TakeoffWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi Burn (Gallons).
        /// </summary>
        public static string TaxiBurn {
            get {
                return ResourceManager.GetString("TaxiBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Components.
        /// </summary>
        public static string ThirdPartyComponents {
            get {
                return ResourceManager.GetString("ThirdPartyComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Help.
        /// </summary>
        public static string ToolsHelp {
            get {
                return ResourceManager.GetString("ToolsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Category.
        /// </summary>
        public static string UtilityCategory {
            get {
                return ResourceManager.GetString("UtilityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Category Color.
        /// </summary>
        public static string UtilityCategoryColor {
            get {
                return ResourceManager.GetString("UtilityCategoryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Category Line Style.
        /// </summary>
        public static string UtilityCategoryLineStyle {
            get {
                return ResourceManager.GetString("UtilityCategoryLineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading XML.
        /// </summary>
        public static string XmlReadError {
            get {
                return ResourceManager.GetString("XmlReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing XML.
        /// </summary>
        public static string XmlWriteError {
            get {
                return ResourceManager.GetString("XmlWriteError", resourceCulture);
            }
        }
    }
}
